<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_name' => 'Seeker',
                'session_id' => 'abma7o208uqs4nmgkg9nlkumqb',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '::1',
                'referer' => 'http://localhost/sadebot/botapi/gui/jquery/?',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 12:44:27',
                'last_update' => '2018-10-18 12:44:27',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_name' => 'Seeker',
                'session_id' => 'mp7837l8fkcg0b6ijf5mvc4f3g',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '::1',
                'referer' => 'http://localhost/sadebot/botapi/gui/jquery/?',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 12:45:22',
                'last_update' => '2018-10-18 12:45:22',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_name' => 'Seeker',
                'session_id' => 'emba6i6dg61l07sjb9ksc0235f',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '::1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 12:45:35',
                'last_update' => '2018-10-18 12:45:35',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_name' => 'Seeker',
                'session_id' => '',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '::1',
                'referer' => 'http://localhost/sadebot/',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 12:46:16',
                'last_update' => '2018-10-18 12:46:16',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_name' => 'Seeker',
                'session_id' => 'ogkfcioltqmmv5n466jvjv8eph',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 14:48:11',
                'last_update' => '2018-10-18 14:48:11',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_name' => 'Seeker',
                'session_id' => 'ljl8vb5o1a710mjqkaernj3d08',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 14:49:31',
                'last_update' => '2018-10-18 14:49:31',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_name' => 'Seeker',
                'session_id' => '1h43rk0qvq8kc9d555vs8m8tem',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-18 14:57:49',
                'last_update' => '2018-10-18 14:57:49',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_name' => 'Seeker',
                'session_id' => 'fiml3860780u0fgh2dilkhq687',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (X11; U; Linux x86_64; pl-PL; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.04 (lucid) Firefox/3.6.13',
                'date_logged_on' => '2018-10-18 14:58:05',
                'last_update' => '2018-10-18 14:58:05',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_name' => 'Seeker',
                'session_id' => 'u2fs1issnos8k5tf91qsjunibl',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (X11; U; Linux x86_64; en-NZ; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.10 (maverick) Firefox/3.6.13',
                'date_logged_on' => '2018-10-18 14:58:29',
                'last_update' => '2018-10-18 14:58:29',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_name' => 'Seeker',
                'session_id' => '2ee36f5hct2kr37npil15rbhu5',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3 like Mac OS X; pl-pl) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8F190 Safari/6533.18.5',
                'date_logged_on' => '2018-10-18 14:58:55',
                'last_update' => '2018-10-18 14:58:55',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_name' => 'Seeker',
                'session_id' => 'c1j7da3n88c1aqi4ffh0hja7al',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (X11; U; Linux i686; ru; rv:1.9.1.3) Gecko/20091020 Ubuntu/9.10 (karmic) Firefox/3.5.3',
                'date_logged_on' => '2018-10-18 15:00:02',
                'last_update' => '2018-10-18 15:00:02',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_name' => 'Seeker',
                'session_id' => '138g8cmq2ks88ifof7ulbtn9sc',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)',
                'date_logged_on' => '2018-10-18 15:00:26',
                'last_update' => '2018-10-18 15:00:26',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_name' => 'Seeker',
                'session_id' => 'dfugo38du92m5poc3ba3se9ko0',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 5.2; rv:2.0b13pre) Gecko/20110304 Firefox/4.0b13pre',
                'date_logged_on' => '2018-10-18 15:01:37',
                'last_update' => '2018-10-18 15:01:37',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_name' => 'Seeker',
                'session_id' => '7k5549ofbkbqqp79of9emk0qqf',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.0; es-ES; rv:1.9.1.9) Gecko/20100315 Firefox/3.5.9 GTB5 (.NET CLR 3.5.30729)',
                'date_logged_on' => '2018-10-19 17:12:26',
                'last_update' => '2018-10-19 17:12:26',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_name' => 'Seeker',
                'session_id' => 'nrd9du2pq314m5q502vljtn220',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 ( ; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
                'date_logged_on' => '2018-10-19 17:12:42',
                'last_update' => '2018-10-19 17:12:42',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_name' => 'Seeker',
                'session_id' => 'h6u7e3bu32j5c6tf7sr0bms678',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; FDM; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; Tablet PC 2.0)',
                'date_logged_on' => '2018-10-19 18:51:02',
                'last_update' => '2018-10-19 18:51:02',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'user_name' => 'Seeker',
                'session_id' => '854ucqn2ek5nqn6ceq9i5pmivl',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.1.6) Gecko/20100118 Gentoo Firefox/3.5.6',
                'date_logged_on' => '2018-10-19 18:53:37',
                'last_update' => '2018-10-19 18:53:37',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_name' => 'Seeker',
                'session_id' => 'hpr35o84ll7loj5747jrg8sttv',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; es-ES; rv:1.9.1) Gecko/20090624 Firefox/3.5 (.NET CLR 3.5.30729)',
                'date_logged_on' => '2018-10-19 18:54:22',
                'last_update' => '2018-10-19 18:54:22',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'user_name' => 'Seeker',
                'session_id' => 'gcni5t5dh7m7kqb45u7q84mjv7',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_4; en-gb) AppleWebKit/528.4+ (KHTML, like Gecko) Version/4.0dp1 Safari/526.11.2',
                'date_logged_on' => '2018-10-19 18:55:50',
                'last_update' => '2018-10-19 18:55:50',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_name' => 'Seeker',
                'session_id' => 'j60kk2c4cifn5ilmk47c6adiiq',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-10-19 18:59:51',
                'last_update' => '2018-10-19 18:59:51',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_name' => 'Seeker',
                'session_id' => 'bk44qd89r90ot4b90hfm3h5uc9',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/534.20 (KHTML, like Gecko) Chrome/11.0.672.2 Safari/534.20',
                'date_logged_on' => '2018-10-19 19:18:28',
                'last_update' => '2018-10-19 19:18:28',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'user_name' => 'Seeker',
                'session_id' => 'NPPEYX7HVODNPFU8',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.11 Safari/534.16',
                'date_logged_on' => '2018-10-22 10:16:20',
                'last_update' => '2018-10-22 10:16:20',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_name' => 'Seeker',
                'session_id' => 'FZOG6T0Q7OKCOR8V',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.2.8) Gecko/20100727 Firefox/3.6.8',
                'date_logged_on' => '2018-11-01 17:30:47',
                'last_update' => '2018-11-01 17:30:47',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_name' => 'Seeker',
                'session_id' => 'CEHDKKY3CWTLFTWY',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; InfoPath.3; .NET4.0C; .NET4.0E; .NET CLR 3.5.30729; .NET CLR 3.0.30729; MS-RTC LM 8)',
                'date_logged_on' => '2018-11-01 18:47:52',
                'last_update' => '2018-11-01 18:47:52',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_name' => 'Seeker',
                'session_id' => '2MNHNRQFUPUOVFKN',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; chromeframe/11.0.696.57)',
                'date_logged_on' => '2018-11-01 20:35:17',
                'last_update' => '2018-11-01 20:35:17',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_name' => 'Seeker',
                'session_id' => 'BDPYECLNNB4FGFFI',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; Zune 4.0)',
                'date_logged_on' => '2018-11-08 11:58:04',
                'last_update' => '2018-11-08 11:58:04',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_name' => 'Friend',
                'session_id' => 'YdKQi',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1b5pre) Gecko/20090517 Firefox/3.5b4pre (.NET CLR 3.5.30729)',
                'date_logged_on' => '2018-11-09 02:03:22',
                'last_update' => '2018-11-09 02:03:22',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_name' => 'Friend',
                'session_id' => '0ay0C0CaZYPWLJ34gY40W3v1ol4VYd6HACUtiwiG',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '127.0.0.1',
                'referer' => 'https://dev.sadebot.com',
            'browser' => 'Mozilla/5.0 (X11; U; CrOS i686 0.9.128; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.339 Safari/534.10',
                'date_logged_on' => '2018-11-09 09:29:41',
                'last_update' => '2018-11-09 09:29:41',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 16:43:04',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_name' => NULL,
                'session_id' => NULL,
                'bot_id' => NULL,
                'chatlines' => NULL,
                'ip' => NULL,
                'referer' => NULL,
                'browser' => NULL,
                'date_logged_on' => '2018-11-11 16:58:57',
                'last_update' => '2018-11-11 16:58:57',
                'state' => NULL,
                'id_role' => NULL,
                'name' => 'djunehor',
                'password' => '$2y$10$Gsa6912VCHA2X.bHgSjW3.fJVlvyq8EM1YC47HEzfzu/NfqRYjPUm',
                'email' => 'djunehor@gmail.com',
                'created_at' => '2018-11-11 16:58:57',
                'updated_at' => '2018-11-12 00:55:38',
                'remember_token' => 'A5jTbQ1Qh4DBYjuvltGds0Y8sbg5Uwci2BsUdQCDjJ8jeNFKHI742bzQIDMK',
            ),
            29 => 
            array (
                'id' => 30,
                'user_name' => NULL,
                'session_id' => NULL,
                'bot_id' => NULL,
                'chatlines' => NULL,
                'ip' => NULL,
                'referer' => NULL,
                'browser' => NULL,
                'date_logged_on' => '2018-11-11 17:17:46',
                'last_update' => '2018-11-11 17:17:46',
                'state' => NULL,
                'id_role' => NULL,
                'name' => 'Afolasade',
                'password' => '$2y$10$HJ5Sn/bgIMhdwSqDDScCjuwdh6hSXWqamnErPgqYkE1JUh8jxJMY.',
                'email' => 'afolasade@gmail.com',
                'created_at' => '2018-11-11 17:17:46',
                'updated_at' => '2018-11-12 00:15:34',
                'remember_token' => 'AbWKrUv3RVLdul7dxzrP67kOXWh8S28D5FZiAq0U5Lx0e8CpoRJ7NN6NYNzX',
            ),
            30 => 
            array (
                'id' => 31,
                'user_name' => 'Omosare',
                'session_id' => 'cTzzP56eqT6TH2ZWO6Ae2gX12nCoG1UVuhjrLhfO',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (X11; U; Linux i686; pt-BR; rv:1.9.2.13) Gecko/20101209 Fedora/3.6.13-1.fc13 Firefox/3.6.13',
                'date_logged_on' => '2018-11-11 17:56:53',
                'last_update' => '2018-11-11 17:56:53',
                'state' => '',
                'id_role' => NULL,
                'name' => 'Bolaji Zacchaeus',
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 17:56:53',
                'updated_at' => '2018-12-02 16:09:21',
                'remember_token' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'user_name' => 'Friend',
                'session_id' => 'c8KMG0ZlD4OCNXQn0YHf3yzVPd8lmGwMVDfyg0go',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)',
                'date_logged_on' => '2018-11-11 18:27:14',
                'last_update' => '2018-11-11 18:27:14',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 18:27:14',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'user_name' => 'Friend',
                'session_id' => 'iWMGUmVCDxTyvTS6CA1MAI7tBHuRA5Q2bkW2L6x2',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; de-DE) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10',
                'date_logged_on' => '2018-11-11 18:55:31',
                'last_update' => '2018-11-11 18:55:31',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 18:55:31',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'user_name' => 'Friend',
                'session_id' => 'l44sWtM2EXzlFDjLLEjOFTeU42iOxlwQfAefZK4C',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Opera/9.80 (Windows NT 5.1; U; MRA 5.5 (build 02842); ru) Presto/2.7.62 Version/11.00',
                'date_logged_on' => '2018-11-11 19:16:41',
                'last_update' => '2018-11-11 19:16:41',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 19:16:41',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'user_name' => 'Friend',
                'session_id' => 'zCr3By9KxgtmygxdhFXFV0pxO6D7tsvA5h6y8mKU',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.11 Safari/534.16',
                'date_logged_on' => '2018-11-11 19:21:12',
                'last_update' => '2018-11-11 19:21:12',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 19:21:12',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'user_name' => 'Friend',
                'session_id' => 'pTyPpLfDFVrCq2iw2CZwnx6vc5zHGaFvLdqIgrFp',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727; Media Center PC 6.0)',
                'date_logged_on' => '2018-11-11 19:26:31',
                'last_update' => '2018-11-11 19:26:31',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 19:26:31',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'user_name' => 'Friend',
                'session_id' => 'XS0kFF2EdyUSCNukEHEnox2sCEbE7LBaEMEBVTFO',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (Windows NT 6.0; WOW64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.699.0 Safari/534.24',
                'date_logged_on' => '2018-11-11 19:34:54',
                'last_update' => '2018-11-11 19:34:54',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 19:34:54',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'user_name' => 'Friend',
                'session_id' => 'ES7r6rtx37cfH9LFuszhTvfXe5HeFUKpbIoLTRfn',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; AskTB5.5)',
                'date_logged_on' => '2018-11-11 20:27:29',
                'last_update' => '2018-11-11 20:27:29',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-11 20:27:29',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'user_name' => 'Friend',
                'session_id' => 'dHIstWXiAbVIB4vyVs9XyvYUZzarIyNik0MG5a8L',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.15) Gecko/20101027 Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/7.0.540.0 Safari/534.10',
                'date_logged_on' => '2018-11-12 00:28:37',
                'last_update' => '2018-11-12 00:28:37',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-12 00:28:37',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'user_name' => 'Friend',
                'session_id' => 'Ryx6InaokNVEtm0HcoRH8meQiux0O1ESih4LI2qW',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; MS-RTC LM 8)',
                'date_logged_on' => '2018-11-12 00:33:51',
                'last_update' => '2018-11-12 00:33:51',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-12 00:33:51',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'user_name' => NULL,
                'session_id' => NULL,
                'bot_id' => NULL,
                'chatlines' => NULL,
                'ip' => NULL,
                'referer' => NULL,
                'browser' => NULL,
                'date_logged_on' => '2018-11-12 00:56:32',
                'last_update' => '2018-11-12 00:56:32',
                'state' => NULL,
                'id_role' => NULL,
                'name' => 'Olatorich',
                'password' => '$2y$10$ZpISgBdXWNjfd1CuJWxlWecem1zOUyRyMqUqq7QCpWpZhAXz0vtBu',
                'email' => 'olatorich@gmail.com',
                'created_at' => '2018-11-11 23:56:32',
                'updated_at' => '2018-11-11 23:56:32',
                'remember_token' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'user_name' => 'Friend',
                'session_id' => 'Pms2SzUj5eOu5BZQpTyTzD4eJinZKfy7odE3HB1A',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '2c0f:f598::8',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-au) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16',
                'date_logged_on' => '2018-11-29 21:37:40',
                'last_update' => '2018-11-29 21:37:40',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-29 21:37:40',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'user_name' => 'Friend',
                'session_id' => 'hbarthgu5nkavdg7a9447vu6u6',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '41.184.177.157',
                'referer' => 'http://botapi.jobzad.com/gui/jquery/?bot_id=1',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
                'date_logged_on' => '2018-11-30 10:55:24',
                'last_update' => '2018-11-30 10:55:24',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2018-11-30 10:55:24',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'user_name' => 'Friend',
                'session_id' => 'fiIwIXiiRDITWgh1uWmfpikbMRYXkXj0jTK2JZhG',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '209.205.211.242',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (X11; U; Linux i686; zh-CN; rv:1.9.1.8) Gecko/20100216 Fedora/3.5.8-1.fc12 Firefox/3.5.8',
                'date_logged_on' => '2019-02-01 18:40:30',
                'last_update' => '2019-02-01 18:40:30',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-02-01 18:40:30',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'user_name' => 'Friend',
                'session_id' => '5a13b3acdc61b9151b6ffc4040dd289f',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '62.210.202.81',
                'referer' => '',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)',
                'date_logged_on' => '2019-05-21 14:26:23',
                'last_update' => '2019-05-21 14:26:23',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-05-21 14:26:23',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'user_name' => 'Friend',
                'session_id' => '9aaacf550ae0978c74de7271c942556e',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '62.210.201.91',
                'referer' => '',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)',
                'date_logged_on' => '2019-05-23 23:35:48',
                'last_update' => '2019-05-23 23:35:48',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-05-23 23:35:48',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'user_name' => 'Friend',
                'session_id' => '77c6e9157e074e7a493f15737da4b34c',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '62.210.202.81',
                'referer' => '',
            'browser' => 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/6.0;)',
                'date_logged_on' => '2019-05-31 00:28:50',
                'last_update' => '2019-05-31 00:28:50',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-05-31 00:28:50',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'user_name' => 'Friend',
                'session_id' => 'YN2yQin2HZukzoR9P6FOuX7Up6reoDZfSgcaX1Ii',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '209.205.211.242',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; SLCC1; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; .NET CLR 1.1.4322)',
                'date_logged_on' => '2019-08-01 20:05:03',
                'last_update' => '2019-08-01 20:05:03',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-08-01 20:05:03',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'user_name' => 'Friend',
                'session_id' => 'zOhZqiVSHHx2QDU2ikjxDDvHsgQsKx4vCuEYp2Vg',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '209.205.211.242',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.2.4) Gecko/20100523 Firefox/3.6.4 ( .NET CLR 3.5.30729)',
                'date_logged_on' => '2019-08-12 06:40:11',
                'last_update' => '2019-08-12 06:40:11',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-08-12 06:40:11',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'user_name' => 'Friend',
                'session_id' => '957c06c3cc7331b9b0a57cb5cc7b00a6',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '36.99.136.138',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36',
                'date_logged_on' => '2019-10-18 09:46:51',
                'last_update' => '2019-10-18 09:46:51',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2019-10-18 09:46:51',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'user_name' => 'Friend',
                'session_id' => 'a428c38d693190d07c4811c75957709c',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '167.114.92.59',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:30:15',
                'last_update' => '2020-06-02 04:30:15',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:30:15',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'user_name' => 'Friend',
                'session_id' => '9202f311a95dd66941ef50b1187957a8',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '167.114.92.59',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:30:16',
                'last_update' => '2020-06-02 04:30:16',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:30:16',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'user_name' => 'Friend',
                'session_id' => 'ab8355c153876dde8b6e33a74fdaabd8',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '167.114.92.59',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:30:23',
                'last_update' => '2020-06-02 04:30:23',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:30:23',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'user_name' => 'Friend',
                'session_id' => '99ad8ddf071340034d615cf67165eac0',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '167.114.92.59',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:30:26',
                'last_update' => '2020-06-02 04:30:26',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:30:26',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'user_name' => 'Friend',
                'session_id' => 'a02e0ae2fa640a19a44602df4be826d8',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '167.114.92.59',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:30:26',
                'last_update' => '2020-06-02 04:30:26',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:30:26',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'user_name' => 'Friend',
                'session_id' => 'e043456cc89197af35325687f2d43899',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '89.163.143.8',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:32:27',
                'last_update' => '2020-06-02 04:32:27',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:32:27',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'user_name' => 'Friend',
                'session_id' => 'a34d0d58f27166a3784ce647a54cfdce',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '137.74.169.241',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:32:40',
                'last_update' => '2020-06-02 04:32:40',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:32:40',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'user_name' => 'Friend',
                'session_id' => 'eb27d068dac29482c0166d84d03fb7a8',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '137.74.169.241',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:32:43',
                'last_update' => '2020-06-02 04:32:43',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:32:43',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'user_name' => 'Friend',
                'session_id' => 'e797ae33f5a6ec8d7a3d813beea2031c',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '137.74.169.241',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:32:45',
                'last_update' => '2020-06-02 04:32:45',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:32:45',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'user_name' => 'Friend',
                'session_id' => '57353cf9f08390df22d035bf057668f0',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '217.79.178.53',
                'referer' => '',
            'browser' => 'Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0',
                'date_logged_on' => '2020-06-02 04:32:48',
                'last_update' => '2020-06-02 04:32:48',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-06-02 04:32:48',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'user_name' => 'Friend',
                'session_id' => '2KAXDpEam21mDxt1tmpN53iYvMpEZBW0ZK45FdPY',
                'bot_id' => 1,
                'chatlines' => 0,
                'ip' => '209.205.211.242',
                'referer' => 'https://sadebot.jobzad.com',
            'browser' => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:2.0b10) Gecko/20110126 Firefox/4.0b10',
                'date_logged_on' => '2020-09-15 23:30:37',
                'last_update' => '2020-09-15 23:30:37',
                'state' => '',
                'id_role' => NULL,
                'name' => NULL,
                'password' => NULL,
                'email' => NULL,
                'created_at' => '2020-09-15 23:30:37',
                'updated_at' => NULL,
                'remember_token' => NULL,
            ),
        ));
        
        
    }
}