<?php

const STATUS_SUCCESS = 200;
const STATUS_FAILED = 500;
const STATUS_BAD_REQUEST = 401;
const STATUS_INTERNAL_SERVER_ERROR = 501;
const STATUS_DB_ERROR = 501;
const STATUS_VALIDATION_FAILED = 402;
const STATUS_NOT_FOUND = 404;
const STATUS_NOT_AUTHORIZED = 405;